[General]
cleanup=true
noauth=true
unpack=true
bootstrap=resolute resolute-updates
aptsources=resolute resolute-updates

[resolute]
packages=sudo sudo-rs sudo-common
packages=kmod dbus apt apt-utils dialog init systemd lsb-release
packages=net-tools ethtool iptables iproute2 iputils-ping ifupdown ssh openssh-server openssh-client tcpdump
packages=openssl adduser passwd bash patch sed bc tar zip gzip dpkg tzdata rsync base-files base-passwd debconf
packages=nano vim-tiny grep i2c-tools dosfstools mtd-utils fdisk time
packages=klibc-utils libc6 u-boot-tools haveged
source=http://ports.ubuntu.com/ubuntu-ports
suite=resolute
components=main restricted universe multiverse

[resolute-updates]
source=http://ports.ubuntu.com/ubuntu-ports
suite=resolute-updates
components=main restricted universe multiverse

